### ISSUE TITLE
Opening/Closing of gripper using gestures 

### ISSUE THREAD

**Issue by StormWulf** [StormWulf/Mobile-Motion-Tracking-Robot-Arm#1]
Figure how to configure the Kinect code to recognize hand gestures for controlling the gripper

**Comment by StormWulf** [comment]
Closed hand servo position `2280`

Opened hand position `1500`

**Comment by JeffRuocco** [comment]
Can now control the gripper using Kinect gestures.  With palm facing the Kinect, an open hand will open the gripper, while a closed hand will close the gripper.
