### ISSUE TITLE
Xbee Wiress Module

### ISSUE THREAD

**Issue by StormWulf** [StormWulf/Mobile-Motion-Tracking-Robot-Arm#2]
Connect the Arduino to the SSC-32 wirelessly with the Xbee module rather than wired

**Comment by StormWulf** [comment]
Need to figure out how to properly communicate the Xbee modules

**Comment by StormWulf** [comment]
https://learn.sparkfun.com/tutorials/xbee-shield-hookup-guide/example-communication-test

**Comment by JeffRuocco** [comment]
I think we need to configure the xbee modules to talk to each other.  I found a video that might help us.
https://www.youtube.com/watch?v=rk5QpzgHXGM

**Comment by StormWulf** [comment]
This might be helpful 
https://github.com/andrewrapp/xbee-arduino

**Comment by JeffRuocco** [comment]
http://forum.arduino.cc/index.php?topic=15718.0

This thread should help us solve our problem.  Basically the xbee header uses the same RX/TX pins as the usb, so they can't be used at the same time.  We have to use software serial to send the servo instructions that the Arduino sends to different pins on the Arduino and then wire those pins to the RX/TX pins on the xbee separately.  Tomorrow I'll look into how to wire the xbee and arduino without using the header and we can try to get it wokring when we meet.
