### ISSUE TITLE
Mobile platform

### ISSUE THREAD

**Issue by StormWulf** [StormWulf/Mobile-Motion-Tracking-Robot-Arm#6]
We need to be able to control the platform wheel servos via the keyboard

**Comment by StormWulf** [comment]
At position `1505` : wheel is paused

At a position of `above 1505` : wheel moves forward

At a position of `below 1505` : wheel moves backward

For now, our ideal servo position for moving backward will be `1460` and `1555` for moving forward

**Comment by StormWulf** [comment]
https://drive.google.com/folderview?id=0B0RCKYn34peHSTZLT08zd21PTUE&usp=sharing&tid=0B0RCKYn34peHamFyTXFudUpqWHM

**Comment by JeffRuocco** [comment]
Movement is possible but needs heavy refinement
